name: Test Javadoc

on:
  push:

jobs:
  build:
    name: Test Javadoc
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Grant execute permission
        run: chmod +x gradlew
      - name: Build robot code
        run: ./gradlew javadoc